# Generated by Django 3.2.9 on 2021-11-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField()),
                ('country', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('zip', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('mal', 'male'), ('fem', 'female'), ('not', 'notset')], max_length=3)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
            ],
            options={
                'ordering': ['user_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'ordering': ['customer'],
            },
        ),
    ]
