# Generated by Django 3.2.9 on 2021-12-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20211227_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
