# Generated by Django 3.2.9 on 2021-11-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grups', '0005_auto_20211116_2024'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title post')),
                ('shortdesc', models.CharField(blank=True, max_length=255, null=True, verbose_name='short description')),
                ('desc', models.TextField()),
                ('location_lat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pub', 'publish'), ('drf', 'draft'), ('del', 'delete'), ('not', 'notset')], default='pub', max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('tag', models.ManyToManyField(to='grups.Tag')),
            ],
        ),
    ]
