# Generated by Django 3.2.9 on 2021-11-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUB', 'publish'), ('DRF', 'draft'), ('DEL', 'delete'), ('NOT', 'notset')], max_length=3),
        ),
    ]
