# Generated by Django 3.2.9 on 2021-11-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0005_auto_20211116_2024'),
        ('customer', '0001_initial'),
        ('post', '0003_featurestory_gallerystory_infographicstory_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='story',
            name='tag',
            field=models.ManyToManyField(to='grups.Tag'),
        ),
    ]
