# Generated by Django 3.2.9 on 2021-11-16 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('post', '0005_auto_20211116_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created_on',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='story',
            name='shortdesc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='story',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
