# Generated by Django 3.2.9 on 2021-11-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0015_category_created_on'),
        ('post', '0006_auto_20211116_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='grups.Category'),
        ),
    ]
