# Generated by Django 3.2.9 on 2021-11-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
