# Generated by Django 3.2.9 on 2021-11-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondary_group',
            old_name='customer',
            new_name='groupp',
        ),
    ]
