# Generated by Django 3.2.9 on 2021-11-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-name'], 'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها '},
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
