# Generated by Django 3.2.9 on 2021-11-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0006_auto_20211116_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(default=None),
        ),
    ]
