# Generated by Django 3.2.9 on 2021-11-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0008_remove_category_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
