# Generated by Django 3.2.9 on 2021-11-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0013_alter_category_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_on',
        ),
    ]
