# Generated by Django 3.2.9 on 2021-12-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0017_alter_category_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_on']},
        ),
    ]
