# Generated by Django 3.2.9 on 2021-12-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0018_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
