# Generated by Django 3.2.9 on 2021-11-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('products', '0004_auto_20211116_1955'),
        ('commentandlike', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment_likes',
            new_name='Products_Comment_likes',
        ),
        migrations.RenameModel(
            old_name='Comment_reply',
            new_name='Products_Comment_reply',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Products_Comments',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Products_Likes',
        ),
    ]
