# Generated by Django 3.2.9 on 2021-11-17 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('commentandlike', '0002_auto_20211116_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_for_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer_reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='customer.customer')),
                ('customer_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='customer.customer')),
            ],
        ),
    ]
