# Generated by Django 3.2.9 on 2021-11-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentandlike', '0003_comment_for_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_comment_likes',
            old_name='date_added',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='products_comment_reply',
            old_name='date_added',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='products_comments',
            old_name='date_added',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='products_likes',
            old_name='date_added',
            new_name='created_on',
        ),
    ]
