# Generated by Django 3.2.9 on 2021-11-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentandlike', '0006_post_comments_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comments',
            name='body',
            field=models.TextField(max_length=300),
        ),
    ]
