# Generated by Django 3.2.9 on 2021-12-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentandlike', '0011_auto_20211202_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_comments',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentandlike.post_comments'),
        ),
    ]
