# Generated by Django 3.2.9 on 2021-12-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentandlike', '0014_userconnections'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_comments',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentandlike.products_comments'),
        ),
        migrations.AddField(
            model_name='products_comments',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
