# Generated by Django 3.2.9 on 2021-12-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentandlike', '0015_auto_20211227_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_comments',
            name='body',
            field=models.TextField(max_length=300),
        ),
    ]
