# Generated by Django 3.2.9 on 2021-11-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liked_list',
        ),
    ]
