# Generated by Django 3.2.9 on 2021-11-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20211116_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket2item',
            old_name='order',
            new_name='Basket',
        ),
        migrations.RenameField(
            model_name='basket2item',
            old_name='products',
            new_name='product',
        ),
    ]
