# Generated by Django 3.2.9 on 2021-12-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20211116_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket2',
            name='shippment',
        ),
    ]
