# Generated by Django 3.2.9 on 2021-12-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20211228_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='Basket',
            new_name='basket',
        ),
    ]
