# Generated by Django 3.2.9 on 2021-12-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_rename_basket_basketitem_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
