# Generated by Django 3.2.9 on 2021-12-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_address_created_on'),
        ('basket', '0010_basket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.address'),
        ),
    ]
