# Generated by Django 3.2.9 on 2021-11-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('grups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=300)),
                ('weight', models.PositiveIntegerField()),
                ('shippment', models.CharField(choices=[('pey', 'peyk_motori'), ('pos', 'post'), ('dgp', 'digikala_post')], max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('secondary_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grups.secondary_group')),
            ],
            options={
                'unique_together': {('customer', 'name')},
            },
        ),
    ]
