# Generated by Django 3.2.9 on 2021-11-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0003_tag'),
        ('products', '0002_products_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(to='grups.Tag'),
        ),
    ]
