# Generated by Django 3.2.9 on 2021-12-23 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_theme'),
        ('grups', '0019_category_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20211116_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='grups.Tag'),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='products',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('shop', 'name')},
        ),
        migrations.RemoveField(
            model_name='products',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='products',
            name='supply',
        ),
    ]
