# Generated by Django 3.2.9 on 2021-12-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_shop_admin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(blank=True, choices=[('chek', 'verified'), ('load', 'in progress'), ('rejc', 'rejected'), ('dele', 'deleted')], max_length=4, null=True),
        ),
    ]
