# Generated by Django 3.2.9 on 2021-12-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0019_category_desc'),
        ('products', '0008_auto_20211223_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='grups.category'),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
