# Generated by Django 3.2.9 on 2021-12-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0019_category_desc'),
        ('products', '0011_products_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='category',
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='grups.Category'),
        ),
    ]
