# Generated by Django 3.2.9 on 2021-12-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0019_category_desc'),
        ('products', '0015_auto_20211227_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(to='grups.Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(to='grups.Tag'),
        ),
    ]
