# Generated by Django 3.2.9 on 2021-12-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0019_category_desc'),
        ('products', '0016_auto_20211228_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(to='grups.Category'),
        ),
    ]
