# Generated by Django 3.2.9 on 2021-12-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_shop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='desc',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
